backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Page"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: true
    files:
      - file: "src/components/home.js"
        label: "Contact Page"
        name: "contact-page"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Job Title, name: jobTitle, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Body, name: body, widget: markdown}


